export const FETCH_CART_REQUEST = "FETCH_CART_REQUEST";
export const FETCH_CART_SUCCESS = "FETCH_CART_SUCCESS";
export const FETCH_CART_ERROR = "FETCH_CART_ERROR";

export const REMOVE_ITEM_REQUEST = "REMOVE_ITEM_REQUEST";
export const REMOVE_ITEM_SUCCESS = "REMOVE_ITEM_SUCCESS";
export const REMOVE_ITEM_ERROR = "REMOVE_ITEM_ERROR";

export const UPDATE_QUANTITY_REQUEST = "UPDATE_QUANTITY_REQUEST";
export const UPDATE_QUANTITY_SUCCESS = "UPDATE_QUANTITY_SUCCESS";
export const UPDATE_QUANTITY_ERROR = "UPDATE_QUANTITY_ERROR";

export const PLACE_ORDER_FROM_CART_REQUEST = "PLACE_ORDER_FROM_CART_REQUEST";
export const PLACE_ORDER_FROM_CART_SUCCESS = "PLACE_ORDER_FROM_CART_SUCCESS";
export const PLACE_ORDER_FROM_CART_ERROR = "PLACE_ORDER_FROM_CART_ERROR";