services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=MualaFuel-database'
      - 'POSTGRES_PASSWORD=${DB_PASSWORD}'
      - 'POSTGRES_USER=${DB_USERNAME}'
    container_name: 'MualaFuel-database'
    ports:
      - '5432:5432'
    networks:
      - MualaFuel-network

networks:
  MualaFuel-network:
    driver: bridge