export const FIND_REQUEST = 'FIND_REQUEST';
export const FIND_SUCCESS = 'FIND_SUCCESS';
export const FIND_ERROR = 'FIND_FAILURE';

export const SAVE_REQUEST = 'SAVE_REQUEST';
export const SAVE_SUCCESS = 'SAVE_SUCCESS';
export const SAVE_ERROR = 'SAVE_FAILURE';

export const UPDATE_REQUEST = 'UPDATE_REQUEST';
export const UPDATE_SUCCESS = 'UPDATE_SUCCESS';
export const UPDATE_ERROR = 'UPDATE_FAILURE';

export const DELETE_REQUEST = 'DELETE_REQUEST';
export const DELETE_SUCCESS = 'DELETE_SUCCESS';
export const DELETE_ERROR = 'DELETE_FAILURE';

export const FIND_BY_ID_REQUEST = 'FIND_BY_ID_REQUEST'
export const FIND_BY_ID_SUCCESS = 'FIND_BY_ID_SUCCESS'
export const FIND_BY_ID_ERROR = 'FIND_BY_ID_ERROR'

export const UPDATE_IMAGE_REQUEST = 'UPDATE_IMAGE_REQUEST'
export const UPDATE_IMAGE_SUCCESS = 'UPDATE_IMAGE_SUCCESS'
export const UPDATE_IMAGE_ERROR = 'UPDATE_IMAGE_ERROR'