export const SEND_CONTACT_REQUEST = 'SEND_CONTACT_REQUEST';
export const SEND_CONTACT_SUCCESS = 'SEND_CONTACT_SUCCESS';
export const SEND_CONTACT_ERROR = 'SEND_CONTACT_ERROR';

export const FETCH_EMAILS_REQUEST = 'FETCH_EMAILS_REQUEST';
export const FETCH_EMAILS_SUCCESS = 'FETCH_EMAILS_SUCCESS';
export const FETCH_EMAILS_ERROR   = 'FETCH_EMAILS_ERROR';

export const DELETE_EMAIL_REQUEST = 'DELETE_EMAIL_REQUEST';
export const DELETE_EMAIL_SUCCESS = 'DELETE_EMAIL_SUCCESS';
export const DELETE_EMAIL_ERROR   = 'DELETE_EMAIL_ERROR';

export const FETCH_EMAIL_BODY_REQUEST  = 'FETCH_EMAIL_BODY_REQUEST';
export const FETCH_EMAIL_BODY_SUCCESS  = 'FETCH_EMAIL_BODY_SUCCESS';
export const FETCH_EMAIL_BODY_ERROR    = 'FETCH_EMAIL_BODY_ERROR';