export const FETCH_ORDERS_REQUEST = "FETCH_ORDERS_REQUEST";
export const FETCH_ORDERS_SUCCESS = "FETCH_ORDERS_SUCCESS";
export const FETCH_ORDERS_ERROR = "FETCH_ORDERS_ERROR";

export const FETCH_ADMIN_ORDERS_REQUEST = "FETCH_ADMIN_ORDERS_REQUEST";
export const FETCH_ADMIN_ORDERS_SUCCESS = "FETCH_ADMIN_ORDERS_SUCCESS";
export const FETCH_ADMIN_ORDERS_ERROR = "FETCH_ADMIN_ORDERS_ERROR";

export const UPDATE_ADMIN_ORDER_REQUEST = "UPDATE_ADMIN_ORDER_REQUEST";
export const UPDATE_ADMIN_ORDER_SUCCESS = "UPDATE_ADMIN_ORDER_SUCCESS";
export const UPDATE_ADMIN_ORDER_ERROR = "UPDATE_ADMIN_ORDER_ERROR";

export const CANCEL_ADMIN_ORDER_REQUEST = "CANCEL_ADMIN_ORDER_REQUEST";
export const CANCEL_ADMIN_ORDER_SUCCESS = "CANCEL_ADMIN_ORDER_SUCCESS";
export const CANCEL_ADMIN_ORDER_ERROR = "CANCEL_ADMIN_ORDER_ERROR";